export const mockGames = [
  {
    id: '1',
    slug: 'gta-vi',
    title: 'Grand Theft Auto VI',
    coverImage: 'https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=600&auto=format&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=1920&auto=format&fit=crop',
    platforms: ['PS5'],
    price: 5499,
    rentPrice: 699,
    isPreorder: true,
    genre: 'Action, Open World',
    shortDescription: 'Grand Theft Auto VI heads to the state of Leonida, home to the neon-soaked streets of Vice City and beyond in the biggest, most immersive evolution of the Grand Theft Auto series yet.',
    rating: 'M',
  },
  {
    id: '2',
    slug: 'spider-man-2',
    title: "Marvel's Spider-Man 2",
    coverImage: 'https://images.unsplash.com/photo-1608889175123-8ee362201f81?q=80&w=600&auto=format&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1608889175123-8ee362201f81?q=80&w=1920&auto=format&fit=crop',
    platforms: ['PS5'],
    price: 4999,
    discountPrice: 3999,
    rentPrice: 399,
    isIncludedInSubscription: true,
    genre: 'Action, Adventure',
    shortDescription: 'Spider-Men Peter Parker and Miles Morales face the ultimate test of strength inside and outside the mask as they fight to save the city, each other and the ones they love.',
    rating: 'T',
  },
  {
    id: '3',
    slug: 'god-of-war-ragnarok',
    title: 'God of War Ragnarök',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=600&auto=format&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1920&auto=format&fit=crop',
    platforms: ['PS5', 'PS4'],
    price: 3999,
    rentPrice: 299,
    isIncludedInSubscription: true,
    genre: 'Action, Adventure, RPG',
    shortDescription: 'Fimbulwinter is well underway. Kratos and Atreus must journey to each of the Nine Realms in search of answers as Asgardian forces prepare for a prophesied battle that will end the world.',
    rating: 'M',
  },
  {
    id: '4',
    slug: 'fc-25',
    title: 'EA SPORTS FC 25',
    coverImage: 'https://images.unsplash.com/photo-1518605368461-1e1c4bc39879?q=80&w=600&auto=format&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1518605368461-1e1c4bc39879?q=80&w=1920&auto=format&fit=crop',
    platforms: ['PS5', 'PS4'],
    price: 4499,
    isNew: true,
    genre: 'Sports',
    shortDescription: 'Experience the most true-to-life football simulation with FC 25.',
    rating: 'E',
  },
  {
    id: '5',
    slug: 'elden-ring',
    title: 'Elden Ring',
    coverImage: 'https://images.unsplash.com/photo-1622819864239-0157924c58df?q=80&w=600&auto=format&fit=crop',
    platforms: ['PS5', 'PS4'],
    price: 3999,
    rentPrice: 399,
    genre: 'Action, RPG',
    shortDescription: 'Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.',
    rating: 'M',
  }
];
