export const mockGames = [
  {
    id: '1',
    slug: 'grand-theft-auto-vi',
    title: 'Grand Theft Auto VI',
    developer: 'Rockstar Games',
    publisher: 'Rockstar Games',
    releaseDate: 'Coming 2025',
    coverImage: 'https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=600&auto=format&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=1920&auto=format&fit=crop',
    platforms: ['PS5'],
    price: 5499,
    rentPrice: 699,
    isPreorder: true,
    genre: 'Action, Open World',
    shortDescription: 'Grand Theft Auto VI heads to the state of Leonida, home to the neon-soaked streets of Vice City.',
    rating: 'M',
  },
  {
    id: '2',
    slug: 'marvels-spider-man-2',
    title: "Marvel's Spider-Man 2",
    developer: 'Insomniac Games',
    publisher: 'Sony Interactive Entertainment',
    releaseDate: 'Oct 20, 2023',
    coverImage: 'https://images.unsplash.com/photo-1608889175123-8ee362201f81?q=80&w=600&auto=format&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1608889175123-8ee362201f81?q=80&w=1920&auto=format&fit=crop',
    platforms: ['PS5'],
    price: 4999,
    discountPrice: 3999,
    isIncludedInSubscription: true,
    genre: 'Action, Adventure',
    shortDescription: 'Spider-Men Peter Parker and Miles Morales face the ultimate test.',
    rating: 'T',
  },
  {
    id: '3',
    slug: 'god-of-war-ragnarok',
    title: 'God of War Ragnarök',
    developer: 'Santa Monica Studio',
    publisher: 'Sony Interactive Entertainment',
    releaseDate: 'Nov 9, 2022',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=600&auto=format&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1920&auto=format&fit=crop',
    platforms: ['PS5', 'PS4'],
    price: 4999,
    discountPrice: 3999,
    genre: 'Action, Adventure',
    shortDescription: 'Embark on an epic and heartfelt journey as Kratos and Atreus struggle with holding on and letting go.',
    rating: 'M',
  },
  {
    id: '4',
    slug: 'ghost-of-yotei',
    title: 'Ghost of Yōtei',
    developer: 'Sucker Punch Productions',
    publisher: 'Sony Interactive Entertainment',
    releaseDate: '2025',
    coverImage: 'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=600&auto=format&fit=crop',
    platforms: ['PS5'],
    price: 4999,
    genre: 'Action Adventure',
    shortDescription: 'A new hero rises in Ghost of Yōtei.',
    rating: 'M',
  },
  {
    id: '5',
    slug: 'astro-bot',
    title: 'ASTRO BOT',
    developer: 'Team ASOBI',
    publisher: 'Sony Interactive Entertainment',
    releaseDate: '2024',
    coverImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=600&auto=format&fit=crop',
    platforms: ['PS5'],
    price: 3999,
    genre: 'Platformer',
    shortDescription: 'Join ASTRO on a supersized space adventure.',
    rating: 'E',
  },
  {
    id: '6',
    slug: 'the-last-of-us-part-i',
    title: 'The Last of Us Part I',
    developer: 'Naughty Dog',
    publisher: 'Sony',
    releaseDate: '2022',
    coverImage: 'https://images.unsplash.com/photo-1622819864239-0157924c58df?q=80&w=600&auto=format&fit=crop',
    platforms: ['PS5'],
    price: 4999,
    discountPrice: 4499,
    genre: 'Action Adventure',
    shortDescription: 'Endure and survive in the acclaimed masterpiece.',
    rating: 'M',
  },
  {
    id: '7',
    slug: 'horizon-forbidden-west',
    title: 'Horizon Forbidden West',
    developer: 'Guerrilla Games',
    publisher: 'Sony',
    releaseDate: '2022',
    coverImage: 'https://images.unsplash.com/photo-1518605368461-1e1c4bc39879?q=80&w=600&auto=format&fit=crop',
    platforms: ['PS5'],
    price: 4999,
    discountPrice: 3499,
    genre: 'Action RPG',
    shortDescription: 'Join Aloy as she braves the Forbidden West.',
    rating: 'T',
  },
  {
    id: '8',
    slug: 'gran-turismo-7',
    title: 'Gran Turismo 7',
    developer: 'Polyphony Digital',
    publisher: 'Sony',
    releaseDate: '2022',
    coverImage: 'https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=600&auto=format&fit=crop',
    platforms: ['PS5'],
    price: 4999,
    discountPrice: 3999,
    genre: 'Racing',
    shortDescription: 'The Real Driving Simulator.',
    rating: 'E',
  }
];

export const mockSubscriptions = [
  {
    id: 'ess',
    name: 'ESSENTIAL',
    price: 499,
    duration: '1 Month',
    description: 'New games to play each month, online multiplayer, exclusive discounts from PlayStation Store and more.',
    features: ['Monthly Games', 'Online Multiplayer', 'Exclusive Discounts', 'Cloud Storage'],
    color: 'from-blue-600 to-blue-400'
  },
  {
    id: 'ext',
    name: 'EXTRA',
    price: 749,
    duration: '1 Month',
    description: 'Discover a huge catalogue of incredible PS4 and PS5 games, plus all the benefits of the Essential plan.',
    features: ['Game Catalogue', 'Ubisoft+ Classics', 'Everything in Essential'],
    color: 'from-yellow-600 to-yellow-400'
  },
  {
    id: 'del',
    name: 'DELUXE',
    price: 849,
    duration: '1 Month',
    description: 'Enjoy all the core PlayStation Plus benefits, hundreds of games in the Game Catalogue, plus exclusive benefits like game trials and the Classics Catalogue.',
    features: ['Classics Catalogue', 'Game Trials', 'Everything in Extra'],
    color: 'from-gray-800 to-gray-500'
  }
];
