export const mockGames = [
  {
    id: '1',
    slug: 'gta-vi',
    title: 'Grand Theft Auto VI',
    developer: 'Rockstar Games',
    publisher: 'Rockstar Games',
    releaseDate: 'Coming 2025',
    coverImage: 'https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=600&auto=format&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1605901309584-818e25960b8f?q=80&w=1920&auto=format&fit=crop',
    platforms: ['PS5'],
    price: 5499,
    rentPrice: 699,
    isPreorder: true,
    genre: 'Action, Open World',
    shortDescription: 'Grand Theft Auto VI heads to the state of Leonida, home to the neon-soaked streets of Vice City and beyond in the biggest, most immersive evolution of the Grand Theft Auto series yet.',
    fullDescription: 'Grand Theft Auto VI continues the series tradition of pushing the boundaries of interactive entertainment. Set in the sprawling state of Leonida, players will explore a massive, meticulously detailed open world. Experience a brand new narrative with dual protagonists, seamless heists, and the most realistic world ever created by Rockstar Games.',
    rating: 'M',
    trailerUrl: 'https://www.youtube.com/embed/QdBZY2fkU-0',
    screenshots: [
      'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=1920&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1920&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1608889175123-8ee362201f81?q=80&w=1920&auto=format&fit=crop',
    ],
    features: ['Single Player', 'Online Multiplayer', 'DualSense Support', '4K HDR'],
  },
  {
    id: '2',
    slug: 'spider-man-2',
    title: "Marvel's Spider-Man 2",
    developer: 'Insomniac Games',
    publisher: 'Sony Interactive Entertainment',
    releaseDate: 'Oct 20, 2023',
    coverImage: 'https://images.unsplash.com/photo-1608889175123-8ee362201f81?q=80&w=600&auto=format&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1608889175123-8ee362201f81?q=80&w=1920&auto=format&fit=crop',
    platforms: ['PS5'],
    price: 4999,
    discountPrice: 3999,
    rentPrice: 399,
    isIncludedInSubscription: true,
    genre: 'Action, Adventure',
    shortDescription: 'Spider-Men Peter Parker and Miles Morales face the ultimate test of strength inside and outside the mask as they fight to save the city, each other and the ones they love.',
    fullDescription: 'Swing, jump and utilize the new Web Wings to travel across Marvel’s New York, quickly switching between Peter Parker and Miles Morales to experience different stories and epic new powers, as the iconic villain Venom threatens to destroy their lives, their city and the ones they love.',
    rating: 'T',
    trailerUrl: 'https://www.youtube.com/embed/bgqGdIoa52s',
    screenshots: [
      'https://images.unsplash.com/photo-1608889175123-8ee362201f81?q=80&w=1920&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1552820728-8b83bb6b773f?q=80&w=1920&auto=format&fit=crop',
    ],
    features: ['Single Player', 'Ray Tracing', 'DualSense Support', '3D Audio'],
  },
  {
    id: '3',
    slug: 'god-of-war-ragnarok',
    title: 'God of War Ragnarök',
    developer: 'Santa Monica Studio',
    publisher: 'Sony Interactive Entertainment',
    releaseDate: 'Nov 9, 2022',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=600&auto=format&fit=crop',
    heroImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1920&auto=format&fit=crop',
    platforms: ['PS5', 'PS4'],
    price: 3999,
    rentPrice: 299,
    isIncludedInSubscription: true,
    genre: 'Action, Adventure, RPG',
    shortDescription: 'Fimbulwinter is well underway. Kratos and Atreus must journey to each of the Nine Realms in search of answers as Asgardian forces prepare for a prophesied battle that will end the world.',
    fullDescription: 'From Santa Monica Studio comes the sequel to the critically acclaimed God of War (2018). Fimbulwinter is well underway. Kratos and Atreus must journey to each of the Nine Realms in search of answers as Asgardian forces prepare for a prophesied battle that will end the world. Along the way they will explore stunning, mythical landscapes, and face fearsome enemies in the form of Norse gods and monsters.',
    rating: 'M',
    screenshots: [
      'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1920&auto=format&fit=crop',
    ],
    features: ['Single Player', 'DualSense Support', '4K Resolution', 'HDR'],
  }
];

export const mockSubscriptions = [
  {
    id: 'ess',
    name: 'ESSENTIAL',
    price: 499,
    duration: '1 Month',
    description: 'New games to play each month, online multiplayer, exclusive discounts from PlayStation Store and more.',
    features: ['Monthly Games', 'Online Multiplayer', 'Exclusive Discounts', 'Cloud Storage'],
    color: 'from-blue-600 to-blue-400'
  },
  {
    id: 'ext',
    name: 'EXTRA',
    price: 749,
    duration: '1 Month',
    description: 'Discover a huge catalogue of incredible PS4 and PS5 games, plus all the benefits of the Essential plan.',
    features: ['Game Catalogue', 'Ubisoft+ Classics', 'Everything in Essential'],
    color: 'from-yellow-600 to-yellow-400'
  },
  {
    id: 'del',
    name: 'DELUXE',
    price: 849,
    duration: '1 Month',
    description: 'Enjoy all the core PlayStation Plus benefits, hundreds of games in the Game Catalogue, plus exclusive benefits like game trials and the Classics Catalogue.',
    features: ['Classics Catalogue', 'Game Trials', 'Everything in Extra'],
    color: 'from-gray-800 to-gray-500'
  }
];
